version: "3"

services:
  client:
    container_name: client
    build: ./client
    image: client
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./client:/usr/src/app
    networks:
      - app-network
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    image: server
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      PORT: 5000
      MONGODB_URL: "mongodb://mongodb:27017/solve_db"
    volumes:
      - ./server:/usr/src/app
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    container_name: database
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: solve_db
    volumes:
      - mongo:/data/db
    networks:
      - app-network

volumes:
  mongo: {}
    
networks:
  app-network: