version: "3"

services:
  mongodb:
    container_name: 3bld_database
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: solve_db
    volumes:
      - ./server/data/mongo/:/data/db
    